development:
  sessions:
    default:
      database: geocoded_providers
      hosts:
        - 0.0.0.0:27017
      raise_not_found_error: false
      options:
        pool_size: 35

procuction:
  sessions:
    default:
      database: geocoded_providers
      hosts:
        - 0.0.0.0:27017
      options:
        pool_size: 35
